export type RfpStatus = "approved" | "negotiation" | "rejected" | "pending";

export interface RfpRow {
  id: string;
  hotel: string;
  brand: string;
  city: string;
  tier: "Luxury" | "Upscale" | "Midscale" | "Economy";
  adr: number;
  cap: number;
  variation: number; // adr vs cap %
  roomNights: number;
  spend: number;
  breakfast: boolean;
  wifi: boolean;
  cancellation: number; // hours
  lra: boolean; // last room availability
  scoreCommercial: number; // 0-100
  scoreCompliance: number; // 0-100
  scoreLocation: number; // 0-100
  scoreTotal: number; // weighted
  status: RfpStatus;
  responseDate: string;
  contact: string;
  notes: string;
}

const HOTELS: Array<Omit<RfpRow, "id" | "scoreTotal" | "variation">> = [
  {
    hotel: "Marriott Paulista",
    brand: "Marriott",
    city: "São Paulo",
    tier: "Upscale",
    adr: 285,
    cap: 290,
    roomNights: 4820,
    spend: 1373700,
    breakfast: true,
    wifi: true,
    cancellation: 24,
    lra: true,
    scoreCommercial: 88,
    scoreCompliance: 95,
    scoreLocation: 92,
    status: "approved",
    responseDate: "2025-03-12",
    contact: "carla.silva@marriott.com",
    notes: "Negociado upgrade gratuito para diretores. Café da manhã incluído em todas as tarifas.",
  },
  {
    hotel: "Hilton Morumbi",
    brand: "Hilton",
    city: "São Paulo",
    tier: "Luxury",
    adr: 342,
    cap: 320,
    roomNights: 2140,
    spend: 731880,
    breakfast: true,
    wifi: true,
    cancellation: 48,
    lra: false,
    scoreCommercial: 62,
    scoreCompliance: 78,
    scoreLocation: 85,
    status: "negotiation",
    responseDate: "2025-03-14",
    contact: "rafael.costa@hilton.com",
    notes: "ADR 6.9% acima do cap. Em renegociação para Q2. LRA não oferecido.",
  },
  {
    hotel: "Pullman Vila Olímpia",
    brand: "Accor",
    city: "São Paulo",
    tier: "Upscale",
    adr: 268,
    cap: 290,
    roomNights: 3210,
    spend: 860280,
    breakfast: true,
    wifi: true,
    cancellation: 24,
    lra: true,
    scoreCommercial: 91,
    scoreCompliance: 90,
    scoreLocation: 88,
    status: "approved",
    responseDate: "2025-03-08",
    contact: "marina.alves@accor.com",
    notes: "Excelente custo-benefício. Localização estratégica próxima à Faria Lima.",
  },
  {
    hotel: "Sheraton WTC",
    brand: "Marriott",
    city: "São Paulo",
    tier: "Upscale",
    adr: 312,
    cap: 290,
    roomNights: 1890,
    spend: 589680,
    breakfast: false,
    wifi: true,
    cancellation: 24,
    lra: false,
    scoreCommercial: 58,
    scoreCompliance: 72,
    scoreLocation: 90,
    status: "negotiation",
    responseDate: "2025-03-15",
    contact: "thiago.melo@marriott.com",
    notes: "Café da manhã não incluso na tarifa negociada. Solicitar revisão.",
  },
  {
    hotel: "Fairmont Copacabana",
    brand: "Accor",
    city: "Rio de Janeiro",
    tier: "Luxury",
    adr: 398,
    cap: 380,
    roomNights: 1240,
    spend: 493520,
    breakfast: true,
    wifi: true,
    cancellation: 48,
    lra: true,
    scoreCommercial: 70,
    scoreCompliance: 88,
    scoreLocation: 95,
    status: "approved",
    responseDate: "2025-03-10",
    contact: "patricia.vieira@accor.com",
    notes: "Tier premium aprovado para C-level. ADR ligeiramente acima do cap justificada por categoria.",
  },
  {
    hotel: "Windsor Atlântica",
    brand: "Windsor",
    city: "Rio de Janeiro",
    tier: "Upscale",
    adr: 295,
    cap: 320,
    roomNights: 2680,
    spend: 790600,
    breakfast: true,
    wifi: true,
    cancellation: 24,
    lra: true,
    scoreCommercial: 85,
    scoreCompliance: 92,
    scoreLocation: 90,
    status: "approved",
    responseDate: "2025-03-09",
    contact: "leonardo.santos@windsor.com",
    notes: "Forte parceiro local. Ofereceu desconto adicional de 4% em pacotes de 3+ noites.",
  },
  {
    hotel: "Hyatt Centric Brickell",
    brand: "Hyatt",
    city: "Miami",
    tier: "Upscale",
    adr: 289,
    cap: 310,
    roomNights: 1820,
    spend: 525980,
    breakfast: false,
    wifi: true,
    cancellation: 24,
    lra: true,
    scoreCommercial: 82,
    scoreCompliance: 86,
    scoreLocation: 87,
    status: "approved",
    responseDate: "2025-03-11",
    contact: "sofia.martinez@hyatt.com",
    notes: "Localização estratégica em Brickell. Café da manhã opcional a US$ 22/dia.",
  },
  {
    hotel: "Four Seasons Buenos Aires",
    brand: "Four Seasons",
    city: "Buenos Aires",
    tier: "Luxury",
    adr: 425,
    cap: 350,
    roomNights: 680,
    spend: 289000,
    breakfast: true,
    wifi: true,
    cancellation: 72,
    lra: false,
    scoreCommercial: 48,
    scoreCompliance: 62,
    scoreLocation: 95,
    status: "rejected",
    responseDate: "2025-03-16",
    contact: "mariana.lopez@fourseasons.com",
    notes: "ADR 21% acima do cap. Política sem LRA. Recomendado fora do programa preferencial.",
  },
  {
    hotel: "Holiday Inn Santiago",
    brand: "IHG",
    city: "Santiago",
    tier: "Midscale",
    adr: 168,
    cap: 195,
    roomNights: 3420,
    spend: 574560,
    breakfast: true,
    wifi: true,
    cancellation: 24,
    lra: true,
    scoreCommercial: 92,
    scoreCompliance: 88,
    scoreLocation: 78,
    status: "approved",
    responseDate: "2025-03-07",
    contact: "andres.rojas@ihg.com",
    notes: "Melhor custo-benefício da região. Volume crescente em viagens operacionais.",
  },
  {
    hotel: "InterContinental Bogotá",
    brand: "IHG",
    city: "Bogotá",
    tier: "Upscale",
    adr: 245,
    cap: 260,
    roomNights: 1560,
    spend: 382200,
    breakfast: true,
    wifi: true,
    cancellation: 48,
    lra: true,
    scoreCommercial: 84,
    scoreCompliance: 90,
    scoreLocation: 86,
    status: "approved",
    responseDate: "2025-03-13",
    contact: "diego.herrera@ihg.com",
    notes: "Renovação automática proposta para 2026. Manutenção de city cap atual.",
  },
  {
    hotel: "Renaissance Polanco",
    brand: "Marriott",
    city: "Cidade do México",
    tier: "Upscale",
    adr: 278,
    cap: 285,
    roomNights: 2240,
    spend: 622720,
    breakfast: true,
    wifi: true,
    cancellation: 24,
    lra: true,
    scoreCommercial: 86,
    scoreCompliance: 91,
    scoreLocation: 89,
    status: "approved",
    responseDate: "2025-03-12",
    contact: "valentina.cruz@marriott.com",
    notes: "Bairro premium. Forte preferência de viajantes seniores.",
  },
  {
    hotel: "Novotel Lima",
    brand: "Accor",
    city: "Lima",
    tier: "Midscale",
    adr: 152,
    cap: 175,
    roomNights: 2890,
    spend: 439280,
    breakfast: true,
    wifi: true,
    cancellation: 24,
    lra: true,
    scoreCommercial: 90,
    scoreCompliance: 87,
    scoreLocation: 75,
    status: "approved",
    responseDate: "2025-03-08",
    contact: "camila.gomez@accor.com",
    notes: "Tarifa competitiva. Bairro de Miraflores, seguro para viajantes.",
  },
  {
    hotel: "Grand Hyatt SP",
    brand: "Hyatt",
    city: "São Paulo",
    tier: "Luxury",
    adr: 365,
    cap: 320,
    roomNights: 980,
    spend: 357700,
    breakfast: true,
    wifi: true,
    cancellation: 48,
    lra: false,
    scoreCommercial: 55,
    scoreCompliance: 70,
    scoreLocation: 88,
    status: "negotiation",
    responseDate: "2025-03-17",
    contact: "ricardo.tanaka@hyatt.com",
    notes: "Tier luxury justificado para alguns C-level. Negociar LRA como contrapartida.",
  },
  {
    hotel: "Ibis Santos Dumont",
    brand: "Accor",
    city: "Rio de Janeiro",
    tier: "Economy",
    adr: 118,
    cap: 140,
    roomNights: 4120,
    spend: 486160,
    breakfast: false,
    wifi: true,
    cancellation: 24,
    lra: true,
    scoreCommercial: 94,
    scoreCompliance: 82,
    scoreLocation: 80,
    status: "approved",
    responseDate: "2025-03-06",
    contact: "bruno.lima@accor.com",
    notes: "Volume alto em viagens operacionais. Café da manhã não incluso por padrão.",
  },
  {
    hotel: "JW Marriott Bogotá",
    brand: "Marriott",
    city: "Bogotá",
    tier: "Luxury",
    adr: 318,
    cap: 290,
    roomNights: 720,
    spend: 228960,
    breakfast: true,
    wifi: true,
    cancellation: 48,
    lra: false,
    scoreCommercial: 60,
    scoreCompliance: 74,
    scoreLocation: 91,
    status: "negotiation",
    responseDate: "2025-03-18",
    contact: "elena.ramirez@marriott.com",
    notes: "ADR 9.7% acima do cap. Sem LRA. Em conversação com sourcing regional.",
  },
  {
    hotel: "Mercure Curitiba Centro",
    brand: "Accor",
    city: "Curitiba",
    tier: "Midscale",
    adr: 175,
    cap: 195,
    roomNights: 1840,
    spend: 322000,
    breakfast: true,
    wifi: true,
    cancellation: 24,
    lra: true,
    scoreCommercial: 88,
    scoreCompliance: 89,
    scoreLocation: 82,
    status: "approved",
    responseDate: "2025-03-09",
    contact: "fernanda.borges@accor.com",
    notes: "Forte presença regional. Renovação sem alteração de tarifa.",
  },
  {
    hotel: "Belmond Copacabana Palace",
    brand: "Belmond",
    city: "Rio de Janeiro",
    tier: "Luxury",
    adr: 580,
    cap: 380,
    roomNights: 320,
    spend: 185600,
    breakfast: true,
    wifi: true,
    cancellation: 72,
    lra: false,
    scoreCommercial: 32,
    scoreCompliance: 55,
    scoreLocation: 98,
    status: "rejected",
    responseDate: "2025-03-19",
    contact: "isabela.duarte@belmond.com",
    notes: "Categoria luxury não justificada para programa corporativo. Fora do escopo preferencial.",
  },
  {
    hotel: "Tryp Higienópolis",
    brand: "Meliá",
    city: "São Paulo",
    tier: "Midscale",
    adr: 195,
    cap: 220,
    roomNights: 2560,
    spend: 499200,
    breakfast: true,
    wifi: true,
    cancellation: 24,
    lra: true,
    scoreCommercial: 87,
    scoreCompliance: 86,
    scoreLocation: 84,
    status: "approved",
    responseDate: "2025-03-10",
    contact: "paulo.henrique@melia.com",
    notes: "Bom mix preço-localização. Renovação automática 2026.",
  },
  {
    hotel: "Radisson Brasília",
    brand: "Radisson",
    city: "Brasília",
    tier: "Upscale",
    adr: 232,
    cap: 250,
    roomNights: 1920,
    spend: 445440,
    breakfast: true,
    wifi: true,
    cancellation: 24,
    lra: true,
    scoreCommercial: 86,
    scoreCompliance: 88,
    scoreLocation: 85,
    status: "approved",
    responseDate: "2025-03-11",
    contact: "juliana.ferreira@radisson.com",
    notes: "Próximo ao Setor Hoteleiro Norte. Forte preferência por viajantes governamentais.",
  },
  {
    hotel: "Hyatt Place Bogotá",
    brand: "Hyatt",
    city: "Bogotá",
    tier: "Midscale",
    adr: 158,
    cap: 180,
    roomNights: 0,
    spend: 0,
    breakfast: true,
    wifi: true,
    cancellation: 24,
    lra: true,
    scoreCommercial: 89,
    scoreCompliance: 85,
    scoreLocation: 78,
    status: "pending",
    responseDate: "2025-03-20",
    contact: "manuel.vega@hyatt.com",
    notes: "Resposta de RFP recente. Aguardando aprovação do comitê de sourcing.",
  },
  {
    hotel: "AC Hotel Porto Alegre",
    brand: "Marriott",
    city: "Porto Alegre",
    tier: "Upscale",
    adr: 218,
    cap: 235,
    roomNights: 1480,
    spend: 322640,
    breakfast: false,
    wifi: true,
    cancellation: 24,
    lra: true,
    scoreCommercial: 84,
    scoreCompliance: 84,
    scoreLocation: 80,
    status: "approved",
    responseDate: "2025-03-12",
    contact: "gustavo.pereira@marriott.com",
    notes: "Café da manhã opcional. Forte preferência em viagens operacionais.",
  },
  {
    hotel: "Ibis Budget Confins",
    brand: "Accor",
    city: "Belo Horizonte",
    tier: "Economy",
    adr: 95,
    cap: 120,
    roomNights: 2340,
    spend: 222300,
    breakfast: false,
    wifi: true,
    cancellation: 12,
    lra: false,
    scoreCommercial: 92,
    scoreCompliance: 76,
    scoreLocation: 70,
    status: "approved",
    responseDate: "2025-03-08",
    contact: "tatiana.rocha@accor.com",
    notes: "Próximo ao aeroporto. Cancelamento restrito (12h). Sem LRA.",
  },
  {
    hotel: "Sofitel Recife",
    brand: "Accor",
    city: "Recife",
    tier: "Luxury",
    adr: 348,
    cap: 310,
    roomNights: 540,
    spend: 187920,
    breakfast: true,
    wifi: true,
    cancellation: 48,
    lra: false,
    scoreCommercial: 56,
    scoreCompliance: 68,
    scoreLocation: 88,
    status: "negotiation",
    responseDate: "2025-03-19",
    contact: "renata.albuquerque@accor.com",
    notes: "ADR acima do cap. Negociando inclusão de LRA e redução de 8%.",
  },
  {
    hotel: "Wyndham Rio Barra",
    brand: "Wyndham",
    city: "Rio de Janeiro",
    tier: "Midscale",
    adr: 188,
    cap: 210,
    roomNights: 1640,
    spend: 308320,
    breakfast: true,
    wifi: true,
    cancellation: 24,
    lra: true,
    scoreCommercial: 85,
    scoreCompliance: 87,
    scoreLocation: 76,
    status: "approved",
    responseDate: "2025-03-10",
    contact: "carolina.dias@wyndham.com",
    notes: "Boa opção para Barra. Pacote corporativo competitivo.",
  },
  {
    hotel: "Holiday Inn Express SP",
    brand: "IHG",
    city: "São Paulo",
    tier: "Midscale",
    adr: 165,
    cap: 185,
    roomNights: 3680,
    spend: 607200,
    breakfast: true,
    wifi: true,
    cancellation: 24,
    lra: true,
    scoreCommercial: 91,
    scoreCompliance: 90,
    scoreLocation: 82,
    status: "approved",
    responseDate: "2025-03-07",
    contact: "felipe.nogueira@ihg.com",
    notes: "Volume alto, custo-benefício excelente. Café da manhã grátis em todas as tarifas.",
  },
  {
    hotel: "Bourbon Convention",
    brand: "Bourbon",
    city: "Foz do Iguaçu",
    tier: "Upscale",
    adr: 245,
    cap: 260,
    roomNights: 980,
    spend: 240100,
    breakfast: true,
    wifi: true,
    cancellation: 24,
    lra: true,
    scoreCommercial: 86,
    scoreCompliance: 85,
    scoreLocation: 83,
    status: "approved",
    responseDate: "2025-03-11",
    contact: "marcelo.kowalski@bourbon.com",
    notes: "Eventos corporativos frequentes na região. Renovação tranquila.",
  },
  {
    hotel: "Meliá Cidade do México",
    brand: "Meliá",
    city: "Cidade do México",
    tier: "Upscale",
    adr: 254,
    cap: 285,
    roomNights: 1320,
    spend: 335280,
    breakfast: true,
    wifi: true,
    cancellation: 24,
    lra: true,
    scoreCommercial: 87,
    scoreCompliance: 88,
    scoreLocation: 85,
    status: "approved",
    responseDate: "2025-03-09",
    contact: "alejandra.morales@melia.com",
    notes: "Localização Reforma. Resposta de RFP completa e dentro do prazo.",
  },
  {
    hotel: "Park Hyatt Buenos Aires",
    brand: "Hyatt",
    city: "Buenos Aires",
    tier: "Luxury",
    adr: 392,
    cap: 350,
    roomNights: 0,
    spend: 0,
    breakfast: true,
    wifi: true,
    cancellation: 72,
    lra: false,
    scoreCommercial: 52,
    scoreCompliance: 65,
    scoreLocation: 94,
    status: "pending",
    responseDate: "2025-03-21",
    contact: "lucia.fernandez@hyatt.com",
    notes: "Aguardando análise. ADR alto, mas localização Recoleta estratégica.",
  },
  {
    hotel: "Pestana Curitiba",
    brand: "Pestana",
    city: "Curitiba",
    tier: "Midscale",
    adr: 162,
    cap: 195,
    roomNights: 1240,
    spend: 200880,
    breakfast: true,
    wifi: true,
    cancellation: 24,
    lra: true,
    scoreCommercial: 90,
    scoreCompliance: 86,
    scoreLocation: 78,
    status: "approved",
    responseDate: "2025-03-08",
    contact: "vanessa.machado@pestana.com",
    notes: "Tarifa competitiva. Programa de fidelidade integrado.",
  },
];

export const RFP_ROWS: RfpRow[] = HOTELS.map((h, i) => {
  const variation = ((h.adr - h.cap) / h.cap) * 100;
  const scoreTotal = Math.round(
    h.scoreCommercial * 0.5 + h.scoreCompliance * 0.3 + h.scoreLocation * 0.2,
  );
  return {
    ...h,
    id: `rfp-${String(i + 1).padStart(3, "0")}`,
    variation,
    scoreTotal,
  };
});